### ISSUE TITLE
can you upload the test video

### ISSUE THREAD

**Issue by renguoyin123** [bamwani/car-counting-and-speed-estimation-yolo-sort-python#1]
Your code is so cool! but I tested it with my own video, and I couldn't see LANE, SPEED, and I couldn't generate final. CSV, please upload your test video,i am looking forward to it.

**Comment by bamwani** [comment]
Sorry for the late reply, Here's the link to the output video: https://drive.google.com/open?id=1Zci9i13Voo9KMhJQyygoZ-kYAVFiaoVQ
Also, the speed won't be show in the screen because we're calculating it in between 2 lines, bu it'll be added in the csv.
Also, note that there are 4 locations in the video, you can delete 3 and edit the first one according to your needs.

**Comment by bamwani** [comment]
@renguoyin123
Sorry for the late reply, Here's the link to the output video: 
https://drive.google.com/open?id=1Zci9i13Voo9KMhJQyygoZ-kYAVFiaoVQ
The speed won't be shown on the screen because we're calculating it in between 2 lines, but it'll be added in the csv.
Also, note that there are 4 locations in the video and so the code(4 IFs), you can delete 3 and edit the first one according to your needs.

**Comment by renguoyin123** [comment]
@bamwani Thanks a lot！
